### ISSUE TITLE
solver and training code

### ISSUE THREAD

**Issue by kylemcdonald** [janesjanes/sketchy#3]
Hi! I'm working with this code for another project. I've pushed some modified notebooks into my repo if you're curious https://github.com/kylemcdonald/sketchy/tree/master/code

Including a example for uploading sketches from the browser to a backend that processes them and returns similar images (Server.ipynb).

I'm interested in re-training the network on a synthetic dataset, where we run some smart edge detection to generate sketches from photos. Is it possible to share the solver and training files (or code) that were used to train the network?

Thanks!

**Comment by janesjanes** [comment]
sorry for the delays, I added the solver and prototxt we used for training. 83b5c645ee61d54e148b9e3a3e57ab0f92db1e3a 

Thanks for sharing your code!

**Comment by kylemcdonald** [comment]
thanks so much! i won't be able to test these right away, so i'm going to close this issue for now and re-open if there are issues.
